# Generated by Django 3.2.9 on 2022-05-29 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCat', models.AutoField(primary_key=True, serialize=False, verbose_name='id de categoria')),
                ('nombreCat', models.CharField(max_length=100, verbose_name='nombre de categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idTipo', models.AutoField(primary_key=True, serialize=False, verbose_name='id del tipo de usuario')),
                ('descripcion', models.CharField(max_length=50, verbose_name='descripcion del tipo de usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='rut de ususario')),
                ('nombre', models.CharField(max_length=50, null=True, verbose_name='nombre ')),
                ('telefono', models.CharField(max_length=15, null=True, verbose_name='telefono')),
                ('contrasenia', models.CharField(max_length=16, null=True, verbose_name='contraseña de usuario')),
                ('mail', models.CharField(max_length=30, null=True, verbose_name='mail de usuario')),
                ('direccion', models.CharField(max_length=30, null=True, verbose_name='direccion')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idVenta', models.AutoField(primary_key=True, serialize=False, verbose_name='id de venta')),
                ('fechaVenta', models.DateField(verbose_name='fecha de la venta')),
                ('totalVenta', models.IntegerField(verbose_name='total de la venta')),
                ('estadoVenta', models.CharField(max_length=40, verbose_name='estado de la venta')),
                ('tipoPago', models.CharField(max_length=40, verbose_name='tipo de pago')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='id producto')),
                ('nombreProducto', models.CharField(max_length=100, null=True, verbose_name='nombre de producto')),
                ('stock', models.IntegerField(verbose_name='cantidad de stock')),
                ('precio', models.IntegerField(verbose_name='precio del producto')),
                ('desc', models.CharField(max_length=2000, verbose_name='descripcion del producto')),
                ('foto', models.ImageField(null=True, upload_to='fotos', verbose_name='Foto del producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idCarrito', models.AutoField(primary_key=True, serialize=False, verbose_name='id de carrito')),
                ('cantidad', models.IntegerField(verbose_name='cantidad de productos en carrito')),
                ('subTotal', models.IntegerField(verbose_name='total del carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
